export{ default as getAllContacts } from './getAllContacts.js'
export{ default as getContactById } from './getContactById.js'
export{ default as addContact } from './addContact.js'
export{ default as updateContactById } from './updateContactById.js'
export{ default as updateStatusContact } from './updateStatusContact.js'
export{ default as deleteContactById } from './deleteContactById.js'